import jsPDF from "jspdf";

interface ToolkitData {
  title: string;
  verse?: string;
  topic?: string;
  audience: string;
  sermonOutline: string;
  objectLesson: string;
  discussionQuestions: string;
  prayerPoints: string;
  kidsVersion: string;
}

export function exportToolkitPDF(data: ToolkitData) {
  const doc = new jsPDF();
  const gold = [201, 168, 76];
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let y = 25;

  function checkPageBreak(needed: number) {
    if (y + needed > 270) {
      doc.addPage();
      y = 20;
    }
  }

  function addSection(title: string, content: string) {
    checkPageBreak(30);
    doc.setFontSize(14);
    doc.setTextColor(gold[0], gold[1], gold[2]);
    doc.text(title, margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(content, maxWidth);
    for (const line of lines) {
      checkPageBreak(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += 8;
  }

  doc.setFontSize(22);
  doc.setTextColor(gold[0], gold[1], gold[2]);
  doc.text("Ministry Toolkit", margin, y);
  y += 10;

  doc.setFontSize(16);
  doc.setTextColor(30, 30, 30);
  const titleLines = doc.splitTextToSize(data.title, maxWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 7 + 2;

  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  const subtitle = [
    data.verse ? `Verse: ${data.verse}` : "",
    data.topic ? `Topic: ${data.topic}` : "",
    `Audience: ${data.audience}`,
  ]
    .filter(Boolean)
    .join(" | ");
  doc.text(subtitle, margin, y);
  y += 12;

  addSection("Sermon Outline", data.sermonOutline);
  addSection("Object Lesson", data.objectLesson);
  addSection("Discussion Questions", data.discussionQuestions);
  addSection("Prayer Points", data.prayerPoints);
  addSection("Kids Version", data.kidsVersion);

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by Ministry Toolkit - Available free on TVR App Store",
    margin,
    285
  );

  const filename = `ministry-toolkit-${data.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.pdf`;
  doc.save(filename);
}
